modLoader = "javafml"
loaderVersion = "[40,)"
license = "MIT"
[[mods]]
modId = "netmusic"
version = "${file.jarVersion}"
displayName = "Net Music Mod"
authors = "TartaricAcid, 郝南村, 琥珀酸, 帕金伊, SQwatermark"
description = "A music player mod"
